import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("rendered: `hoge/fuga/layout.tsx`");

  return (
    <>
      {children}
    </>
  );
}
